---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible_role_minikube_ubuntu_min
    image: ubuntu:14.04

provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: ubuntu_min

verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
