---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible_role_minikube_default
    image: ubuntu:20.04

provisioner:
  name: ansible

verifier:
  name: testinfra
