---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible_role_minikube_debian_max
    image: debian:11

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  config_options:
    defaults:
      inject_facts_as_vars: false

scenario:
  name: debian_max

verifier:
  name: testinfra
  directory: ../default/tests
