---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible_role_minikube_debian_min
    image: debian:8

provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: debian_min

verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
