---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible_role_minikube_ubuntu_max
    image: ubuntu:20.04

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  config_options:
    defaults:
      inject_facts_as_vars: false

scenario:
  name: ubuntu_max

verifier:
  name: testinfra
  directory: ../default/tests
